version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "8080:80"
    environment:
      - PORT=${PORT}
    depends_on:
      - blue_app
      - green_app
    networks:
      - app_network

  blue_app:
    image: ${BLUE_IMAGE}
    container_name: blue_app
    ports:
      - "8081:${PORT}"
    environment:
      - PORT=${PORT}
      - APP_POOL=blue
      - RELEASE_ID=${RELEASE_ID_BLUE}
    networks:
      - app_network

  green_app:
    image: ${GREEN_IMAGE}
    container_name: green_app
    ports:
      - "8082:${PORT}"
    environment:
      - PORT=${PORT}
      - APP_POOL=green
      - RELEASE_ID=${RELEASE_ID_GREEN}
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
